In [1]:
import numpy as np

In [16]:
a = np.array([0.1,0.9])
b = np.array([[0.2,0.8],[0.3,0.7]])
print(a)
print(b)
print(a[:,np.newaxis].T)

[ 0.1  0.9]
[[ 0.2  0.8]
 [ 0.3  0.7]]
[[ 0.1  0.9]]


In [21]:
np.concatenate((a[:,np.newaxis].T,b),axis=0)

array([[ 0.1,  0.9],
       [ 0.2,  0.8],
       [ 0.3,  0.7]])