In [1]:
import numpy as np

In [16]:
a = np.array([0.1,0.9])
b = np.array([[0.2,0.8],[0.3,0.7]])
print(a)
print(b)
print(a[:,np.newaxis].T)

[ 0.1  0.9]
[[ 0.2  0.8]
 [ 0.3  0.7]]
[[ 0.1  0.9]]


In [21]:
np.concatenate((a[:,np.newaxis].T,b),axis=0)

array([[ 0.1,  0.9],
       [ 0.2,  0.8],
       [ 0.3,  0.7]])

In [11]:
[i for x in zip([1]*10,range(10)) for i in x]

[1, 0, 1, 1, 1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 1, 7, 1, 8, 1, 9]

In [13]:
204516-204464

52

In [14]:
list(range(10))[:3]

[0, 1, 2]

In [17]:
int(236456456.3454364356//2)

118228228